#ifndef XML_ENGIE_CLIENT_GLOBAL_H
#define XML_ENGIE_CLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(XML_ENGIE_CLIENT_LIBRARY)
#  define XML_ENGIE_CLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define XML_ENGIE_CLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // XML_ENGIE_CLIENT_GLOBAL_H
